services:
  bot:
    build: .
    volumes:
      - './models:/root/.node-llama-cpp/models:rw'
    env_file:
      - .env
    depends_on:
      - cache
  cache:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - './redis-data:/data'

  cache-admin:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - './redis-insight-data:/data'
