services:
  bot:
    image: storyspin-bot
    build: .
    volumes:
      - './models:/root/.node-llama-cpp/models:ro'
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
