services:
  bot:
    image: storyspin-bot
    build: .
    volumes:
      - './models:/usr/share/app/models:ro'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
