FROM continuumio/miniconda3

WORKDIR /usr/src/app

COPY stable_diffusion_api.py .

RUN apk add build-base git rust cargo openssl-dev

RUN --mount=type=cache,target=/root/.cache \
    conda env create -f environment.yaml

RUN conda env activate sd-discord

EXPOSE 5000

CMD ["flask", "--app", "stable_diffusion_api.py", "run"]
